default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: deploy
  password: pointer
development:
  <<: *default
  database: myapi2_development
test:
  <<: *default
  database: myapi2_test
production:
  <<: *default
  database: myapi2_production
